// GENERATED by firmware/tools/gen_pal_frames.py from Clawdmeter's claudepix
// animation data -- do not hand-edit. See docs/specs/2026-07-17-pal-screen-design.md.
#pragma once
#include <stdint.h>

#define PAL_FRAME_W 20
#define PAL_FRAME_H 20
#define PAL_FRAME_PX 400
#define PAL_FRAME_BYTES (PAL_FRAME_PX * 3)  // LV_IMG_CF_TRUE_COLOR_ALPHA

typedef enum {
  PAL_ANIM_EXPRESSION_SLEEP,
  PAL_ANIM_EXPRESSION_SURPRISE,
  PAL_ANIM_EXPRESSION_WINK,
  PAL_ANIM_IDLE_BLINK,
  PAL_ANIM_IDLE_BREATHE,
  PAL_ANIM_IDLE_LOOK_AROUND,
  PAL_ANIM_DANCE_SWAY,
  PAL_ANIM_DANCE_BOUNCE,
  PAL_ANIM_WORK_CODING,
  PAL_ANIM_WORK_THINK,
  PAL_ANIM_COUNT,
} pal_anim_id_t;

typedef struct {
  uint16_t frame_count;
  const uint8_t (*frames)[PAL_FRAME_BYTES];  // frame_count entries, RGB565+A8 pixels
  const uint16_t* holds_ms;                    // frame_count entries
} pal_anim_t;

extern const pal_anim_t PAL_ANIMS[PAL_ANIM_COUNT];
