#!/usr/bin/env python3
"""Regenerate ui/screens/pal_frames.{h,c} from Clawdmeter's claudepix animation JSON.

Source: https://github.com/HermannBjorgvin/Clawdmeter tools/claudepix_data/*.json
(20x20 pixel-art frames, palette-indexed in the source JSON; see
docs/specs/2026-07-17-pal-screen-design.md for the licensing caveat on this art before
touching it).

Frames are expanded here to LV_IMG_CF_TRUE_COLOR_ALPHA (RGB565 + 8-bit alpha, 3
bytes/pixel) rather than kept indexed: LVGL 8.4's zoom/rotate transform (lv_draw_sw_img.c
decode_and_draw) only takes the whole-buffer-available fast path -- with a direct
img_data pointer -- for TRUE_COLOR*/RGB565A8 formats. LV_IMG_CF_INDEXED_8BIT always
routes through the line-by-line decode fallback, which has no zoom support at all, so an
indexed sprite silently renders at its native 20x20 size instead of scaling up.

Usage:
  1. Download the 10 JSON files listed in ANIMS below from the URL above into a local dir.
  2. python3 gen_pal_frames.py <dir-with-json-files>
  3. Regenerates ../src/ui/screens/pal_frames.h and pal_frames.c in place.
"""
import json
import os
import sys

# (json filename stem, C enum suffix) -- order fixes the PAL_ANIM_* enum values.
ANIMS = [
    ("expression_sleep", "EXPRESSION_SLEEP"),
    ("expression_surprise", "EXPRESSION_SURPRISE"),
    ("expression_wink", "EXPRESSION_WINK"),
    ("idle_blink", "IDLE_BLINK"),
    ("idle_breathe", "IDLE_BREATHE"),
    ("idle_look_around", "IDLE_LOOK_AROUND"),
    ("dance_sway", "DANCE_SWAY"),
    ("dance_bounce", "DANCE_BOUNCE"),
    ("work_coding", "WORK_CODING"),
    ("work_think", "WORK_THINK"),
    ("dance_djmix", "DANCE_DJMIX"),
]

FRAME_W = 20
FRAME_H = 20
FRAME_PX = FRAME_W * FRAME_H
BYTES_PER_PX = 3  # LV_IMG_CF_TRUE_COLOR_ALPHA @ LV_COLOR_DEPTH=16: RGB565 lo, RGB565 hi, alpha


def hex_to_rgb565_bytes(hexstr):
    h = hexstr.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    rgb565 = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    return (rgb565 & 0xFF, (rgb565 >> 8) & 0xFF)  # little-endian: lo byte, hi byte


def palette_to_px(palette):
    # index -> (lo, hi, alpha) triple, per lv_draw_sw_img.c's TRUE_COLOR_ALPHA decode.
    out = []
    for entry in palette:
        if entry == "transparent":
            out.append((0, 0, 0x00))
        else:
            lo, hi = hex_to_rgb565_bytes(entry)
            out.append((lo, hi, 0xFF))
    return out


def load_anim(data_dir, stem):
    with open(os.path.join(data_dir, f"{stem}.json")) as f:
        d = json.load(f)
    assert d["frame_count"] == len(d["frames"]), stem
    px_palette = palette_to_px(d["palette"])
    frames = []
    for fr in d["frames"]:
        grid = fr["grid"]
        assert len(grid) == FRAME_H and all(len(row) == FRAME_W for row in grid), stem
        pixels = bytearray(FRAME_PX * BYTES_PER_PX)
        i = 0
        for row in grid:
            for idx in row:
                lo, hi, a = px_palette[idx]
                pixels[i] = lo
                pixels[i + 1] = hi
                pixels[i + 2] = a
                i += BYTES_PER_PX
        frames.append((bytes(pixels), fr["hold"]))
    return frames


def c_bytes(b):
    return ",".join(str(x) for x in b)


def main():
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(1)
    data_dir = sys.argv[1]
    out_dir = os.path.join(os.path.dirname(__file__), "..", "src", "ui", "screens")

    h_path = os.path.join(out_dir, "pal_frames.h")
    c_path = os.path.join(out_dir, "pal_frames.c")

    with open(h_path, "w") as h:
        h.write(
            "// GENERATED by firmware/tools/gen_pal_frames.py from Clawdmeter's claudepix\n"
            "// animation data -- do not hand-edit. See docs/specs/2026-07-17-pal-screen-design.md.\n"
            "#pragma once\n#include <stdint.h>\n\n"
            f"#define PAL_FRAME_W {FRAME_W}\n#define PAL_FRAME_H {FRAME_H}\n"
            f"#define PAL_FRAME_PX {FRAME_PX}\n"
            f"#define PAL_FRAME_BYTES (PAL_FRAME_PX * {BYTES_PER_PX})  // LV_IMG_CF_TRUE_COLOR_ALPHA\n\n"
            "typedef enum {\n"
        )
        for stem, suffix in ANIMS:
            h.write(f"  PAL_ANIM_{suffix},\n")
        h.write("  PAL_ANIM_COUNT,\n} pal_anim_id_t;\n\n")
        h.write(
            "typedef struct {\n"
            "  uint16_t frame_count;\n"
            "  const uint8_t (*frames)[PAL_FRAME_BYTES];  // frame_count entries, RGB565+A8 pixels\n"
            "  const uint16_t* holds_ms;                    // frame_count entries\n"
            "} pal_anim_t;\n\n"
            "extern const pal_anim_t PAL_ANIMS[PAL_ANIM_COUNT];\n"
        )

    with open(c_path, "w") as c:
        c.write(
            "// GENERATED by firmware/tools/gen_pal_frames.py -- do not hand-edit.\n"
            '#include "pal_frames.h"\n\n'
        )
        all_frames = {}
        for stem, _suffix in ANIMS:
            frames = load_anim(data_dir, stem)
            all_frames[stem] = frames
            c.write(f"static const uint8_t {stem}_frames[][PAL_FRAME_BYTES] = {{\n")
            for pixels, _hold in frames:
                c.write(f"  {{{c_bytes(pixels)}}},\n")
            c.write("};\n")
            c.write(
                f"static const uint16_t {stem}_holds[] = "
                f"{{{','.join(str(hv) for _p, hv in frames)}}};\n\n"
            )

        c.write("const pal_anim_t PAL_ANIMS[PAL_ANIM_COUNT] = {\n")
        for stem, suffix in ANIMS:
            frames = all_frames[stem]
            c.write(f"  [PAL_ANIM_{suffix}] = {{ {len(frames)}, {stem}_frames, {stem}_holds }},\n")
        c.write("};\n")

    print(f"wrote {h_path}\nwrote {c_path}")


if __name__ == "__main__":
    main()
